name: Master CI/CD

on:
  push:
    branches:
      - '*'
      - '!*/**'

jobs:
  workflow:
    runs-on: ubuntu-latest

    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.head_ref == 'dev')

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2

      - name: Install
        run: |
          yarn set version berry
          yarn install --immutable

      - name: Prettier
        run: yarn prettier:check

      - name: ESLint
        run: yarn lint

      - name: Unit test
        run: yarn test


