name: Master CI/CD

on:
  push:
    branches:
      - '*'
      - '!*/**'

jobs:
  workflow:
    runs-on: ubuntu-latest

    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.head_ref == 'dev')

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'yarn'

      - name: Install
        env:
          YARN_CHECKSUM_BEHAVIOR: update
        run: |
          yarn set version berry
          yarn install --immutable

      - name: Prettier
        run: yarn prettier:check

      - name: ESLint
        run: yarn lint

      - name: Tests
        env:
          REVENTEX_MONGO_CONNECTION_USERNAME: ${{ secrets.REVENTEX_MONGO_CONNECTION_USERNAME }}
          REVENTEX_MONGO_CONNECTION_PASSWORD: ${{ secrets.REVENTEX_MONGO_CONNECTION_PASSWORD }}
        run: yarn test


